### ISSUE TITLE
رفتن به پیوی کاربر

### ISSUE THREAD

**Issue by ahr1384** [geeksesi/guess_emoji_telegram_bot#15]
سلام
چطوری میشه از طریق چت ایدی پیوی کاربر رو بگیریم حتی وقتی یوزر نیم نداره

**Comment by geeksesi** [comment]
سلام.
ببین وقتی طرف یوزر نیم نداره که یعنی نداره و نمی تونی بهش پیام بدی.

اما وقتی یوزر نیم داره و مثل من فقط chat_id رو ذخیره کردی. یدونه متد تلگرام هست :
https://core.telegram.org/bots/api#getchat

که من اینجا یدونه کامند براش ساختم : 
https://github.com/geeksesi/guess_emoji_telegram_bot/blob/6ac4496bbd00281eba0163b2fa437bfde2bf8ca3/app/Helper/InputHelper.php#L192
https://github.com/geeksesi/guess_emoji_telegram_bot/blob/6ac4496bbd00281eba0163b2fa437bfde2bf8ca3/app/Controller/Admin/GetUserByChatIdController.php#L8

اگر هم کاربرت یوزر نیم نداشت می تونی یه کامند دیگه بذاری. بهش با chat_id پیام بدی و ازش درخواست کنی باهات تماس بگیره :)
