### ISSUE TITLE
املاء کلمه

### ISSUE THREAD

**Issue by geeksesi** [geeksesi/guess_emoji_telegram_bot#20]
یه مشکلی که داریم اینه که بازی خیلی وابستس به املاء کلمه.

بازی هایی مثل آمیرزا و... خیلی ساده ای قضیه رو حل کردن. اما ما اینجا نمی تونیم ای راه حل اونها استفاده کنیم.

باید به شکلی باشه که اگر طرف اون کلمه رو با املاء متفاوت وارد کرد ازش قبول کنیم.

دوستان اگر راه حلی دارید در خدمتیم

**Comment by geeksesi** [comment]
یه چیزی که خودم  به ذهنم رسیده بود : 
وقتی داریم مرحله رو وارد می کنیم حالت های مختلف کلمه رو هم وارد کنیم در حد توان مثلا 5 - 6 تا حالت کلمه با املا های مختلف رو بزنم و هر کدوم رو که فرستاد قبول کنه.

**Comment by geeksesi** [comment]
یه چیزی که علی مولایی توی توییتر گفته بود استفاده کردن از جایگشت 
https://twitter.com/molaei_ali/status/1506610439018491915?s=20&t=BEnY7Nbp4mU4ch3PJTE_sw

خیلی ایده ای در مورد پیاده سازی این ندارم. اما فکر می کنم راه حل بدی نباشه.

**Comment by geeksesi** [comment]
حالت های ساده ‌ای که فعلا می تونیم هندل کنیم : 
- [ ] حذف فاصله ها
- [ ] حذف نیم فاصله
- [ ] تبدیل حروف کیبرد عربی به فارسی

اینا گمونم با جایگشت و اینکه یه جدول داشته باشیم به ازای هر سوال بر اساس جوابش یه سری جواب جنریت بشه داخل اون جدول که ورودی ها با اون جدول چک بشن
- [ ] ساخت جدول جواب ها
- [ ] ریفکتور کردن سیستم چک کردن جواب
- [ ] ساختن دستور برای ساخت حالت های مختلف جواب بر اساس سوال
- [ ] توی اضافه کردن سوال از چندین جواب پشتیبانی کنه سوال

**Comment by geeksesi** [comment]
@llabbasmkhll 
عباس جان مرسی بابت مرج ریکوست.

**Comment by llabbasmkhll** [comment]
❤️❤️
اینکه چندتا جواب ذخیره بشه رو بیخیال شدم
چون به نظرم رسید خود جواب رو هم نرمال کنم مشکل حل میشه 
اگر باز میبینی نیازه اضافش کنیم بگو

**Comment by geeksesi** [comment]
نه به نظر منم نیاز نیست چندتا جواب رو چک کنیم همین قضیه رواله
