### ISSUE TITLE
مشکل در پروفایل بعضی کاربرا

### ISSUE THREAD

**Issue by llabbasmkhll** [geeksesi/guess_emoji_telegram_bot#33]
یه سری کاربرا ( از جمله خودم ) عکس پروفایلشون نمیاد . 

![image](https://user-images.githubusercontent.com/86796762/162615957-5406c18d-1804-4074-a5e5-3588d3ac9ad0.png)

**Comment by geeksesi** [comment]
عباس سیستم هر اروری که بده می فرستتش پیوی من.
یه بار دیدم خیلی اسپم شده، چک کردم مشکل از گرفتن آواتار بود.

البته خب الان برای تو فکر کنم مسئله این باشه که دیگه برای گرفتن آواتارت درخواست نمی زنه.

بذاریم همینجوری بمونه. گرفتن آواتار خیلی چیز واجبی نیست فعلا. بخش ادیت رو که گذاشتیم اوکی میشه قضیه
